<?php

require "common-code-shared.php";

/* sending SMS through PHP

cogSMS ($mobile, $body, $access_token);

parameters:

$mobile = receipient mobile
$body = message. may contain <br> tags for new lines
$access_token = Your API key (also known as access_token) generated by Cognifront system

Returns: JSON encoded response
*/

echo cogSMS ("9657461778", "New documents uploaded<br><br><br> From:kyc", "fb43eed0574191fca87f8bed7be8c057");
?>